version: '3.8'
services:
  mf_drawer:
    build: ./mf_drawer
    ports:
      - "8081:80"
  mf_videos:
    build: ./mf_videos
    ports:
      - "8082:80"
  host:
    build: ./host
    ports:
      - "8080:80"